apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: kustomize-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp-container
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
